language: node_js
node_js:
  - stable
sudo: false
services:
  - mongodb
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: YusEYo4jIn2A8nQFxvEToVRlrUka9KoiVuqO0P3yrxfPn1CccNnb0WuAlNpsRPP8TTFzYEZdEGywlVXpb1bT20eWIJrx1UatX6vKEBo7ih9tAoDXTy8tnTt2jg+xvw4jrlYOPXGNHDM0beSNfLTL0HljI3XW5xb7mZ/z40ME1qxAif19uZfwJ0Ni2v3AHvFnjyg2riE52ErirXzeSfHkJS+XtpOnbao9T8wDA/UjwJX+Dlwf5C6fZjVVQdYBfUyeQEL//3gsKWrhZcVlDftDYQhRZvw4FRCTdYZ3+YpOyuAgAfEt+TxfxVbe6Ce1OIVeTnCjxGEA2S+D974+ne+ykmOuH+f4Y3VR2EFBmqquj1CIDTlcG/VnkxRihQVJKbXYmveA0XkTQ/dwK1opfwCFl3yQdXr+nmzTYg+kg5I0D1PqWbEc1KPH9M1Jk2pDW45wCP/DdEX4mBhoFoSiTkvzwb+ZFzsjVOG6ozMAjKrcg6gXVeH4O+A4n5P43W31kJjVZgVIPuJEi8gT8JBrb7QvtWAd7mT/c8fbfjjN1q+bUWSpqHEa4Bku04YCigo3ZEU64g71qcmFmR1hqV6VVXNCkQZeAZ4kDD4phqQ0EAQyo4OGROvEQ3/eIqe3TB65KPVZ334Pw+do9iTHvOAZ23y+FgMJx7cZr4JAxGeUEYAj5Z4=
  app: athlete-application
  on:
    repo: HighFivesFoundation/athlete-application
    branch: master
